### ISSUE TITLE
document observability stack/setup

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/akdc#117]
- should be part of https://github.com/retaildevcrews/akdc/issues/98

**Comment by aflinchb** [comment]
Have some brain-dump docs here:
https://github.com/retaildevcrews/edge-gitops/blob/atx-fleet/observability-base.md
https://github.com/retaildevcrews/edge-gitops/blob/atx-fleet/observability.md

Not sure where this should live.

**Comment by bartr** [comment]
I moved them to the docs folder and synched to main

We have a process that syncs the main branch, including docs, so this will ensure every fleet has the latest and greatest
