### ISSUE TITLE
What is the Reason for returning nil from runTargetsDeployE function on error?

### ISSUE THREAD

**Issue by maniSbindra** [retaildevcrews/akdc#182]
The function runTargetsDeployE has a Signature "func runTargetsDeployE(cmd *cobra.Command, args []string) error". In this function there are 3 instances similar to 
```
if err != nil {
.
.
return nil
}
```
. The link below highlights the referred code. I wanted to know if there is a reason to return nil from the function on error? or should these instances be returning an error instead?
 
https://github.com/retaildevcrews/akdc/blob/3c184b23d9434f941a68a0672d8d6447cd533e6f/src/kic/cmd/targets/targets-deploy.go#L31-L55

Thanks.

**Comment by bartr** [comment]
- you have to add a project or it won't appear on the board
- we'll triage tomorrow
- IIRC, the caller needs some refactoring to handle the error
- or, it could just be a bug

**Comment by bartr** [comment]
The handler calls that function. If you return an error, Cobra will display the usage information. For known error conditions, returning nil is a cleaner display.
