### ISSUE TITLE
update fluent bit yaml

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/akdc#187]
Update fleet fluent-bit deployment and secrets to use the fluent-bit loki output plugin.  Involves switching from using grafana/fluent-bit-plugin-loki:latest to fluent/fluent-bit:1.9.0)

I noticed the image we were using from the grafana registry hadn't been updated in ~6 months and is not updating to use the latest fluent-bit.

**Comment by aflinchb** [comment]
Updates found here:

https://github.com/retaildevcrews/edge-gitops/blob/apps/apps/fluent-bit/autogitops/dev/fluent-bit.yaml
