### ISSUE TITLE
VoE - mixed content bug

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/akdc#246]
- webmodule has a mixed secure / insecure content bug in the wc:// link

**Comment by kev-ms** [comment]
Error loading https content: 

`useWebSocket.ts:13 Mixed Content: The page at '[https://central-tx-atx-f01.cseretail.com/home/getStarted'](https://central-tx-atx-f01.cseretail.com/home/getStarted%27) was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://central-tx-atx-f01.cseretail.com/api/notifications/'. This request has been blocked; this endpoint must be available over WSS.`


Workaround: 
- Go to browser site settings
- Privacy & Security
- Change insecure Contnet from `Blocked` to `Allow`
<img width="688" alt="image" src="https://user-images.githubusercontent.com/71272427/166947989-bbf9c64e-7a8e-47c3-bcb3-f883fb6a8db6.png">
