### ISSUE TITLE
Spike: Cluster monitoring for scenarios where edge clusters doesn't allow incoming traffic

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/akdc#445]
AD has a challenge with cluster monitoring as they're not likely to allow incoming requests to store clusters. Current monitoring works by WebValidate sending HTTP requests to heartbeat and other applications running in the cluster. This wouldn't work if the clusters block incoming connections. There are two suggestions/thoughts that came as part of the discussions.

- Use a message broker that'll allow an agent/application running in the cluster to respond to monitoring and health check requests.
- Have an agent or the apps in the clusters to send health status regularly and look for absence of logs.

Both of these approaches and its feasibility need to be evaluated and tried out.

**Comment by bartr** [comment]
dupe of #170

**Comment by aflinchb** [comment]
closing as dupe
